// This is the pattern "112P51" from https://copy.sh/life/.
const rle = `#C Generated by copy.sh/life
x = 33, y = 33, rule = B3/S23
10bo11bo$4b2o3bob2o7b2obo3b2o$4b2o5b2o7b2o5b2o$9bob2o7b2obo$b2o6b2o11b
2o6b2o$b2o6b2o3bo3bo3b2o6b2o$13b3ob3o$15bobo$$bob3o21b3obo$o3b2o21b2o
3bo$b3o25b3o$b3o25b3o$6bo19bo$5b2o19b2o$6b2o17b2o$$6b2o17b2o$5b2o19b2o
$6bo19bo$b3o25b3o$b3o25b3o$o3b2o21b2o3bo$bob3o21b3obo$$15bobo$13b3ob3o
$b2o6b2o3bo3bo3b2o6b2o$b2o6b2o11b2o6b2o$9bob2o7b2obo$4b2o5b2o7b2o5b2o$
4b2o3bob2o7b2obo3b2o$10bo11bo!`;

export default rle;
